# Generated by Django 4.1.1 on 2024-02-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='rating',
            field=models.CharField(blank=True, choices=[('TV-Y', 'TV-Y'), ('R', 'R'), ('TV-Y FV', 'TV-Y FV'), ('PG-13', 'PG-13'), ('G', 'G'), ('NC-17', 'NC-17'), ('TV-14', 'TV-14'), ('TV-Y7', 'TV-Y7'), ('TV-MA', 'TV-MA'), ('PG', 'PG')], default='', help_text='Select movie/show rating.', max_length=10, verbose_name='Movie/show Rating'),
        ),
    ]
